name: PCDS Standard Testing

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  standard:
    uses: pcdshub/pcds-ci-helpers/.github/workflows/python-standard.yml@master
    secrets: inherit
    with:
      # The workflow needs to know the package name.  This can be determined
      # automatically if the repository name is the same as the import name.
      package-name: "hutch_python"
      # Extras that will be installed for both conda/pip:
      testing-extras: ""
      # Extras to be installed only for conda-based testing:
      conda-testing-extras: "ipython=8.4.0"
      # Extras to be installed only for pip-based testing:
      # Set numpy<2 for now, remove when xraylib updates
      pip-testing-extras: "ipython==8.4.0 numpy<2"
      # System packages to be installed only for conda-based testing:
      conda-system-packages: ""
      # System packages to be installed only for pip-based testing:
      pip-system-packages: "libkrb5-dev"
      # System packages to be installed only for documentation:
      docs-system-packages: "pandoc"
      # Set if using setuptools-scm for the conda-build workflow
      use-setuptools-scm: true
